# Generated by Django 5.1 on 2025-12-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_observation_verification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
