# Generated by Django 5.1 on 2025-12-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_observer',
            field=models.BooleanField(default=True),
        ),
    ]
