- name: Execute remote ssh commands
uses: appleboy/ssh-action@master
with:
    host: ${{ secrets.EC2_HOST }}  # 1. No extra spaces here
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
        chmod +x /home/ubuntu/deploy.sh
        /home/ubuntu/deploy.sh
