name: Deploy to EC2 (DEBUG)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "START DEPLOY DEBUG"

      - name: Debug secrets
        run: |
          echo "EC2_HOST='${{ secrets.EC2_HOST }}'"
          echo "EC2_USERNAME='${{ secrets.EC2_USERNAME }}'"
          [ -z "${{ secrets.EC2_SSH_KEY }}" ] && echo "EC2_SSH_KEY is EMPTY" || echo "EC2_SSH_KEY OK"

      - name: Stop here
        run: exit 1
